### ISSUE TITLE
Add functional tests for bionic + juju 2.9

### ISSUE THREAD

**Issue by aieri** [canonical/charm-prometheus-juju-exporter#67]
While the snap has a dedicated 2.9 channel, the charm is only testing juju 3.4 and 3.5.

Nishant reports failures on bionic installations:
```
unit-prometheus-juju-exporter-0: 11:06:28 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-prometheus-juju-exporter-0: 11:06:28 WARNING unit.prometheus-juju-exporter/0.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-prometheus-juju-exporter-0: 11:06:28 ERROR unit.prometheus-juju-exporter/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 279, in <module>
    main(PrometheusJujuExporterCharm)
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 64, in wrapper
    if isinstance(self.unit.status, ActiveStatus) and not exporter_running:
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/model.py", line 443, in status
    self._status = StatusBase.from_name(s['status'], s['message'])
  File "/var/lib/juju/agents/unit-prometheus-juju-exporter-0/charm/venv/ops/model.py", line 1131, in from_name
    return cls._statuses[name](message)
KeyError: 'error'
```

We should add the bionic + 2.9 combo to the CI and investigate the failure

**Comment by chanchiwai-ray** [comment]
Can you provide the revision of the charm?
